build:debian-latest:
  image: debian:latest
  stage: build
  before_script:
    - apt update && apt -y install make autoconf gfortran libopenmpi-dev cmake
  script:
    - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=install -S . -B build
    - cmake --build build
    - cmake --build build --target test
    - cmake --build build --target install
  artifacts:
    paths:
      - install/

build:nixpkgs-glibc-2.26:
  image: nixos/nix:latest
  stage: build
  script: 
    - nix-build nix/shell-glibc-2.26.nix -A ovni
