build:debian-testing:
  image: debian:testing
  tags:
    - docker
  stage: build
  before_script:
    - apt update && apt -y install make autoconf gfortran libopenmpi-dev cmake
  script:
    - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=install -S . -B build
    - cmake --build build
    - CTEST_OUTPUT_ON_FAILURE=1 cmake --build build --target test
    - cmake --build build --target install
  artifacts:
    paths:
      - install/

build:rt-tests:
  stage: build
  tags:
    - nix
  script:
    - nix build -L --tarball-ttl 0 --file nix/rt.nix bsc.ovni-rt

build:old-gcc:
  stage: build
  tags:
    - nix
  script:
    - nix build -L --tarball-ttl 0 --file nix/rt.nix bsc.oldOvnis

build:old-gcc-no-lto:
  stage: build
  tags:
    - nix
  script:
    - nix build -L --tarball-ttl 0 --file nix/rt.nix bsc.oldOvnisNoLTO

build:old-gcc-release:
  stage: build
  tags:
    - nix
  script:
    - nix build -L --tarball-ttl 0 --file nix/rt.nix bsc.oldOvnisRelease
