build:debian-latest:
  image: debian:latest
  stage: build
  before_script:
    - apt update && apt -y install make autoconf gfortran libopenmpi-dev cmake
  script:
    - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=install -S . -B build
    - cmake --build build
    - CTEST_OUTPUT_ON_FAILURE=1 cmake --build build --target test
    - cmake --build build --target install
  artifacts:
    paths:
      - install/

build:old-glibc:
  image: nixos/nix:2.9.2
  stage: build
  script: 
    - nix-build nix/old-glibc.nix

build:nosv-tests:
  image:
    name: nixos/nix:2.9.2
  stage: build
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add /dev/fd/0
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - cat /proc/sys/user/max_user_namespaces || true
  script: 
    - nix --extra-experimental-features "nix-command impure-derivations ca-derivations" --option sandbox false build -L --impure --file nix/nosv.nix
