build:debian-latest:
  image: debian:latest
  stage: build
  before_script:
    - apt update && apt -y install make autoconf gfortran libopenmpi-dev cmake
  script:
    - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=install -S . -B build
    - cmake --build build
    - CTEST_OUTPUT_ON_FAILURE=1 cmake --build build --target test
    - cmake --build build --target install
  artifacts:
    paths:
      - install/

build:old-glibc:
  image: nixos/nix:latest
  stage: build
  script: 
    - nix-build nix/old-glibc.nix
